name: CI

on: [push, pull_request]

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [12, 14, 16]
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1

    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}

    - name: Install and Test
      run: |
        npm install
        npm run test
